import { css } from '@/styled-system/css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Prompkit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark" className={css({
      scrollBehavior: 'smooth', 
      background: "fill.primary",
      color: "text.primary",
    })}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
